debug:
  enabled: false
autosave:
  enabled: true # It is recommended to use autosave
  interval: 60 # Every 60 seconds
database:
  type: sqlite # sqlite/mysql/postgresql
  host: localhost
  port: 3306
  database: my_database
  user: user
  password: password
messages_configuration: 'messages.yml'